name = "bias"
version = "0.1.0"
description = "bias — observation filtered through subjectivity, made structural."
licences = ["Apache-2.0"]
# Hex requires an SPDX identifier. The actual governing terms are in REAL_LICENSE.md.
repository = { type = "github", user = "systemic-engineering", repo = "bias" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
